<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>image_flip_bosch.ImgFlip</RootNamespace>
    <AssemblyName>ImgFlip</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="11.0.0-rc.1.26425.128" />
  </ItemGroup>

</Project>
